
package view;

import javax.swing.JFileChooser;

/**
 *
 * @author h4ck3r
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        chooser = new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlArchivos = new javax.swing.JPanel();
        btnEscogerFicheros = new javax.swing.JButton();
        panelScrool = new javax.swing.JScrollPane();
        lstFicheros = new javax.swing.JList<>();
        btnEscogerTodos = new javax.swing.JButton();
        txtPesoF = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        lblCreado = new javax.swing.JLabel();
        txtFCreado = new javax.swing.JTextField();
        pnlContraseña = new javax.swing.JPanel();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnMosContraseña = new javax.swing.JButton();
        btnSavePassword = new javax.swing.JButton();
        btnLoadPassword = new javax.swing.JButton();
        btnDecifrarF = new javax.swing.JButton();
        btnCifrarF = new javax.swing.JButton();
        pgbProgreso = new javax.swing.JProgressBar();
        lblNotificador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CryptoPro");

        pnlArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivo"));

        btnEscogerFicheros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chooseFiles.png"))); // NOI18N
        btnEscogerFicheros.setText("Escoger ficheros");

        panelScrool.setViewportView(lstFicheros);

        btnEscogerTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selecetAll.png"))); // NOI18N
        btnEscogerTodos.setToolTipText("");

        lblPeso.setText("Peso");

        lblCreado.setText("Creado");

        javax.swing.GroupLayout pnlArchivosLayout = new javax.swing.GroupLayout(pnlArchivos);
        pnlArchivos.setLayout(pnlArchivosLayout);
        pnlArchivosLayout.setHorizontalGroup(
            pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchivosLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnEscogerFicheros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
            .addGroup(pnlArchivosLayout.createSequentialGroup()
                .addGroup(pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelScrool))
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesoF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblCreado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFCreado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEscogerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        pnlArchivosLayout.setVerticalGroup(
            pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchivosLayout.createSequentialGroup()
                .addComponent(btnEscogerFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelScrool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnEscogerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)))
                .addGroup(pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addGroup(pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(pnlArchivosLayout.createSequentialGroup()
                        .addGroup(pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoF)
                            .addComponent(lblPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pnlContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        lblContraseña.setText("Contraseña");

        btnMosContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N

        btnSavePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savePassword.png"))); // NOI18N
        btnSavePassword.setText("Guardar Contraseña");

        btnLoadPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadPassword.png"))); // NOI18N
        btnLoadPassword.setText("Cargar Contraseña");

        javax.swing.GroupLayout pnlContraseñaLayout = new javax.swing.GroupLayout(pnlContraseña);
        pnlContraseña.setLayout(pnlContraseñaLayout);
        pnlContraseñaLayout.setHorizontalGroup(
            pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMosContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContraseñaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnSavePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(btnLoadPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        pnlContraseñaLayout.setVerticalGroup(
            pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContraseñaLayout.createSequentialGroup()
                .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContraseñaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContraseña)
                            .addComponent(txtContraseña))
                        .addGap(8, 8, 8))
                    .addGroup(pnlContraseñaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMosContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnDecifrarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/decrypFILES.png"))); // NOI18N
        btnDecifrarF.setText("Decifrar Ficheros");

        btnCifrarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/encryptFiles.png"))); // NOI18N
        btnCifrarF.setText("Cifrar Ficheros");

        pgbProgreso.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pgbProgreso.setForeground(new java.awt.Color(0, 255, 0));
        pgbProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pgbProgreso.setRequestFocusEnabled(false);
        pgbProgreso.setStringPainted(true);

        lblNotificador.setText("-------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnCifrarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(btnDecifrarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                    .addComponent(pgbProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNotificador, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCifrarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecifrarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(pgbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotificador)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCifrarF;
    public javax.swing.JButton btnDecifrarF;
    public javax.swing.JButton btnEscogerFicheros;
    public javax.swing.JButton btnEscogerTodos;
    public javax.swing.JButton btnLoadPassword;
    public javax.swing.JButton btnMosContraseña;
    public javax.swing.JButton btnSavePassword;
    public javax.swing.JLabel lblContraseña;
    public javax.swing.JLabel lblCreado;
    public javax.swing.JLabel lblNotificador;
    public javax.swing.JLabel lblPeso;
    public javax.swing.JList<String> lstFicheros;
    public javax.swing.JScrollPane panelScrool;
    public javax.swing.JProgressBar pgbProgreso;
    public javax.swing.JPanel pnlArchivos;
    public javax.swing.JPanel pnlContraseña;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtFCreado;
    public javax.swing.JTextField txtPesoF;
    // End of variables declaration//GEN-END:variables
   
    public javax.swing.JFileChooser chooser;
    
    
}
